{% set name = "libensemble" %}
{% set version = "0.7.0" %}
{% set build = 0 %}
{% set sha256 = "bf2f3b68abd276aa2a818fbda9baaf1e970dc4419f0858e7685985c291d2b0a8" %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

# prioritize nompi variant via build number
{% if mpi == 'nompi' %}
{% set build = build + 100 %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Libensemble/libensemble/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  # noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

  # add build string so packages can depend on
  # mpi or nompi variants
  # dependencies:
  # `pkg * mpi_mpich_*` for mpich
  # `pkg * mpi_*` for any mpi
  # `pkg * nompi_*` for no mpi
  {% if mpi == 'nompi' %}
  {% set mpi_prefix = "nompi" %}
  {% else %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% endif %}
  string: {{ mpi_prefix }}_py{{ py }}h{{ PKG_HASH }}_{{ build }}

  run_exports:
    # strict runtime dependency on build-time MPI flavor
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - {{ mpi }}  # [mpi != 'nompi']
    - nlopt
    - numpy
    - petsc4py   # [mpi != 'nompi' and not win]
    - python
    - scipy
    - mpi4py     # [mpi != 'nompi']

test:
  imports:
    - libensemble.libE

about:
  home: https://libensemble.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library to coordinate the concurrent evaluation of dynamic ensembles of calculations

  description: |
    libEnsemble is a Python library to coordinate the concurrent evaluation
    of dynamic ensembles of calculations. The library is developed to use
    massively parallel resources to accelerate the solution of design,
    decision, and inference problems and to expand the class of problems that
    can benefit from increased concurrency levels.
    libEnsemble aims for: Extreme scaling, Resilience/fault tolerance,
    Monitoring/killing jobs (and recovering resources), Portability and
    flexibility, Exploitation of persistent data/control flow.
  dev_url: https://github.com/Libensemble/libensemble

extra:
  recipe-maintainers:
    - jlnav
    - jmlarson1
    - shuds13
